version: '3.8'

services:
  mongo:
    container_name: mongodb
    image: mongo:latest
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: chat
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - mongo:/data/db/
    networks:
      - chatty

  backend:
    container_name: backend
    depends_on:
      - mongo
    build: .
    restart: on-failure
    ports:
      - '8080:8080'
    environment:
      MONGO_HOST: mongodb
    networks:
      - chatty

  frontend:
    container_name: frontend
    depends_on:
      - backend
    build:
      context: ./chatty-frontend
      dockerfile: Dockerfile
      args:
        REACT_APP_BACKEND_URL: backend:8080
    ports:
      - '3000:8080'
    networks:
      - chatty

networks:
  chatty:

volumes:
  mongo:
    driver: local